// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJq6p8YUB6sGhQffDrcRLVptkcMfDICXY',
    appId: '1:570277258860:web:099dceda4efd09e4f29a49',
    messagingSenderId: '570277258860',
    projectId: 'mychatapp-81bc2',
    authDomain: 'mychatapp-81bc2.firebaseapp.com',
    storageBucket: 'mychatapp-81bc2.appspot.com',
    measurementId: 'G-CZ7DZW12P9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWnxdeDd-AL91Hvt52YjeqZlxGMgdxv6A',
    appId: '1:570277258860:android:9431cc359125b7aef29a49',
    messagingSenderId: '570277258860',
    projectId: 'mychatapp-81bc2',
    storageBucket: 'mychatapp-81bc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpOOIrngmG_kVkx4RTD0wD66X-M6YiqsU',
    appId: '1:570277258860:ios:22acc4ad054faa1cf29a49',
    messagingSenderId: '570277258860',
    projectId: 'mychatapp-81bc2',
    storageBucket: 'mychatapp-81bc2.appspot.com',
    iosBundleId: 'com.example.mychatApp',
  );
}
